import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ethan Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <header className={styles.header}>
          <p>Software Developer</p>
        </header>
        <nav className={styles.navbar}>
          <ul>
            <li className={styles.work}>Work</li>
            <li className={styles.about}>About</li>
            <li className={styles.contact}>Contact</li>
          </ul>
        </nav>

        <div className={styles.leftSide}>
          <title className={styles.title}>Ethan Pierce</title>
          <Image
            src='/public/code.png'
            height={40}
            width={20}
            alt='block_of_code'
          />
        </div>
        <div className={styles.rightSide}>
          <Image
            src='/public/keyboard.jpg'
            alt='mechanical-keyboard'
            height={40}
            width={20}
          />
        </div>
      </main>
    </div>
  );
}
