import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { hiddenText } from '../animations/transition';
import { useRef, useEffect } from 'react';
import { gsap } from 'gsap';

export default function Home() {
  const navAnim = useRef(null);
  const headerAnim = useRef(null);
  const panelAnim = useRef(null);

  // const tl = gsap.timeline();

  const handleClick = () => {
    hiddenText(navAnim);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Ethan Pierce || Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <header className={styles.header}>
          <p>Software Developer</p>
        </header>
        <nav className={styles.navbar} ref={(el) => (navAnim = el)}>
          <ul>
            <li className={styles.work} onClick={handleClick}>
              Work
            </li>
            <li className={styles.about}>About</li>
            <li className={styles.contact}>Contact</li>
          </ul>
        </nav>

        <div className={styles.leftSide}>
          <title className={styles.title}>Ethan Pierce</title>
          {/* <Image
            src='/public/code.png'
            height={40}
            width={20}
            alt='block_of_code'
          /> */}
        </div>
        <div className={styles.rightSide}>
          {/* <Image
            src='/public/keyboard.jpg'
            alt='mechanical-keyboard'
            height={40}
            width={20}
          /> */}
        </div>
      </main>
    </div>
  );
}
